### PR TITLE
docs: fix trivial typos

### PR DESCRIPTION
**Pull request by tomsaleeba**

### CODE REVIEW

**Comment by raimohanska** [comment]
Thanks! The root files are unfortunately generated, so the fixes need to go into source files, see README.

**Comment by tomsaleeba** [comment]
Whoops, sorry for not reading the README.

I've updated the PR with two commits. Updates to the content and then the generated content, but that's touch a lot of files so if you want me to remove that commit, I can.

**Comment by raimohanska** [comment]
Thanks! I merged the primary commit and generated the site again. Been a while since doing that. Thanks for the help!

Having generated stuff in version control is not a very bright idea and causes this kinda inconvenience to contributors, sorry for that. At the time we just couldn't come up with a better solution. I you have an idea, lemme know :)

**Comment by tomsaleeba** [comment]
I know what it's like, sometimes you just have to do what works.

I'm not an authority on this but if you're looking for alternatives, you could build a CI/CD pipeline with GitHub Actions. On every commit to master, it would run the build process then push the built files out to GitHub Pages, which is what I assume you're using to serve the site. I see you have the `gh-pages` branch, so the "push the built files" could be to commit those files to the `gh-pages` branch. That way you don't need a separate store for static, built files but you also avoid having generated files in the `master` branch.

**Pull request closed without merging**
